[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
leptos = { workspace = true, features = ["ssr"] }
leptos_actix.workspace = true

actix-web.workspace = true
pretty_env_logger.workspace = true
tokio.workspace = true
log.workspace = true
leptos_meta = { version = "0.7.7" }
leptos_router = { version = "0.7.7" }
actix-files = "0.6.6"
roux = "2.2.14"
dotenvy = "0.15.7"
reqwest = "0.12.20"
