[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel-async.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
ulid.workspace = true

diesel-derive-enum = { version = "3.0.0-beta.1", features = ["postgres"] }
futures-util = "0.3.33"
rustls = { version = "0.23.42", features = ["ring"] }
tokio-postgres = "0.7.18"
tokio-postgres-rustls = "0.14.0"
